global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: api-gateway
    static_configs:
      - targets: ['host.docker.internal:3000']

  - job_name: auth
    static_configs:
      - targets: ['host.docker.internal:3001']

  - job_name: order
    static_configs:
      - targets: ['host.docker.internal:3002']

  - job_name: restaurant
    static_configs:
      - targets: ['host.docker.internal:3003']

  - job_name: kitchen
    static_configs:
      - targets: ['host.docker.internal:3004']

  - job_name: payment
    static_configs:
      - targets: ['host.docker.internal:3005']

  - job_name: delivery
    static_configs:
      - targets: ['host.docker.internal:3006']

  - job_name: notification
    static_configs:
      - targets: ['host.docker.internal:3007']
