apiVersion: v2
name: order
description: Order service for Food Ordering System
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - order
  - express
  - microservices
maintainers:
  - name: Food Ordering System Team
