apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: food-ordering
data:
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318/v1/traces"
  OTEL_TRACES_EXPORTER: "otlp"
  AUTH_SERVICE_URL: "http://auth:3001"
  ORDER_SERVICE_URL: "http://order:3002"
  RESTAURANT_SERVICE_URL: "http://restaurant:3003"
