apiVersion: v2
name: auth
description: Authentication service for Food Ordering System
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - auth
  - express
  - microservices
maintainers:
  - name: Food Ordering System Team
